# Generated by Django 4.1.5 on 2023-06-03 19:11

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
