# Generated by Django 4.1.5 on 2023-06-03 19:12

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapapi', '0002_farmer_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='country',
            field=django_countries.fields.CountryField(default='IN', max_length=2),
        ),
    ]
